options:
  merge-default-rules: false
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  mixins-before-declarations: 0
  placeholder-in-extend: 0
  brace-style:
    - 1
    -
      style: stroustrup
  nesting-depth:
    - 1
    -
      max-depth: 5
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  no-color-literals: 0
  no-vendor-prefixes: 0
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 4
  property-sort-order:
    - 0
  quotes:
    - 2
    -
      style: double
